<div style="display:none" id="wd1005">
<div class="ad_time-modal-wrap">
<h3>各駅発車時刻一覧<span>List of departure times</span></h3>
<table>
	<tr>
		<th>S01</th>
		<th>新静岡</th>
		<th>Shin-Shizuoka</th>
		<th>10:20</th>
	</tr>
	<tr>
		<th>S02</th>
		<td>日吉町</td>
		<td>Hiyoshicho</td>
		<td>10:21</td>
	</tr>
	<tr>
		<th>S03</th>
		<td>音羽町</td>
		<td>Otowacho</td>
		<td>10:22</td>
	</tr>
	<tr>
		<th>S04</th>
		<td>春日町</td>
		<td>Kasugacho</td>
		<td>10:24</td>
	</tr>
	<tr>
		<th>S05</th>
		<td>柚木</td>
		<td>Yunoki</td>
		<td>10:25</td>
	</tr>
	<tr>
		<th>S06</th>
		<td>長沼</td>
		<td>Naganuma</td>
		<td>10:27</td>
	</tr>
	<tr>
		<th>S07</th>
		<td>古庄</td>
		<td>Furusho</td>
		<td>10:28</td>
	</tr>
	<tr>
		<th>S08</th>
		<td>県総合運動場</td>
		<td>Pref. Sports Park</td>
		<td>10:30</td>
	</tr>
	<tr>
		<th>S09</th>
		<td>県立美術館前</td>
		<td>Pref. Art Museum</td>
		<td>10:32</td>
	</tr>
	<tr>
		<th>S10</th>
		<td>草薙</td>
		<td>Kusanagi</td>
		<td>10:34</td>
	</tr>
	<tr>
		<th>S11</th>
		<td>御門台</td>
		<td>Mikadodai</td>
		<td>10:36</td>
	</tr>
	<tr>
		<th>S12</th>
		<td>狐ケ崎</td>
		<td>Kitsunegasaki</td>
		<td>10:37</td>
	</tr>
	<tr>
		<th>S13</th>
		<td>桜橋</td>
		<td>Sakurabashi</td>
		<td>10:40</td>
	</tr>
	<tr>
		<th>S14</th>
		<td>入江岡</td>
		<td>Irieoka</td>
		<td>10:41</td>
	</tr>
	<tr>
		<th>S15</th>
		<td>新清水</td>
		<td>Shin-Shimizu</td>
		<td>10:43</td>
	</tr>
</table>
</div>
</div>
