<div style="display:none" id="wd719">
<div class="ad_time-modal-wrap">
<h3>各駅発車時刻一覧<span>List of departure times</span></h3>
<table>
	<tr>
		<td>S01</td>
		<td>新静岡</td>
		<td>Shin-Shizuoka</td>
		<td>7:56</td>
	</tr>
	<tr>
		<td>S02</td>
		<td>日吉町</td>
		<td>Hiyoshicho</td>
		<td>7:57</td>
	</tr>
	<tr>
		<td>S03</td>
		<td>音羽町</td>
		<td>Otowacho</td>
		<td>7:58</td>
	</tr>
	<tr>
		<td>S04</td>
		<td>春日町</td>
		<td>Kasugacho</td>
		<td>8:00</td>
	</tr>
	<tr>
		<td>S05</td>
		<td>柚木</td>
		<td>Yunoki</td>
		<td>8:01</td>
	</tr>
	<tr>
		<td>S06</td>
		<td>長沼</td>
		<td>Naganuma</td>
		<td>8:03</td>
	</tr>
	<tr>
		<td>S07</td>
		<td>古庄</td>
		<td>Furusho</td>
		<td>8:05</td>
	</tr>
	<tr>
		<td>S08</td>
		<td>県総合運動場</td>
		<td>Pref. Sports Park</td>
		<td>8:07</td>
	</tr>
	<tr>
		<td>S09</td>
		<td>県立美術館前</td>
		<td>Pref. Art Museum</td>
		<td>8:09</td>
	</tr>
	<tr>
		<td>S10</td>
		<td>草薙</td>
		<td>Kusanagi</td>
		<td>8:10</td>
	</tr>
	<tr>
		<td>S11</td>
		<td>御門台</td>
		<td>Mikadodai</td>
		<td>8:12</td>
	</tr>
	<tr>
		<td>S12</td>
		<td>狐ケ崎</td>
		<td>Kitsunegasaki</td>
		<td>8:14</td>
	</tr>
	<tr>
		<td>S13</td>
		<td>桜橋</td>
		<td>Sakurabashi</td>
		<td>8:17</td>
	</tr>
	<tr>
		<td>S14</td>
		<td>入江岡</td>
		<td>Irieoka</td>
		<td>8:18</td>
	</tr>
	<tr>
		<td>S15</td>
		<td>新清水</td>
		<td>Shin-Shimizu</td>
		<td>8:20</td>
	</tr>
</table>
</div>
</div>
